services:
  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpass@123#
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass@123#
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 8080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=dbuser
      - WORDPRESS_DB_PASSWORD=dbpass@123#
      - WORDPRESS_DB_NAME=wordpress_db
volumes:
db_data:
wp_data:
